def smiley():
    print("  ----- ")
    print(".'     '.")
    print("/ o   o \ ")
    print("|        |")
    print("| \    / |")
    print("\  '__'  /")
    print(" '_______'")
def sad():
    print("  ----- ")
    print(".'     '.")
    print("/ o   o \ ")
    print("|        |")
    print("| .-----.|")
    print(" \'     '/")
    print(" ._______.")
def suprise():
    print("  ----- ")
    print(".'     '.")
    print("/ o   o \ ")
    print("|        |")
    print("|\ ⡠⠤⢄ / |")
    print("\  ⢄⠀⢀⠀ /")
    print(" '__⠈____'")
smiley()
sad()
suprise()